### ISSUE TITLE
URGENT TASKS: OSTATECZNA PAPIERKOLOGIA

### ISSUE THREAD

**Issue by czeskij** [czeskij/GraIO#13]
ogólnie jest takie coś (x znaczy że zrobione, ksywka to przypisanie):

> protokół zalożycielski x
> opis funkcjonalny aplikacji (yarp)  
> mapa myśli x
> model konceptualny (yarp) 
> harmonogram x
> identyfikacja aktorów (czech)
> diagram klas (lambert)
> bezpieczeństwo (czech)
> niezawodność 10 przypadków (lambert)
> plan testów (czech)
> testy (czech)
> raporty testów (czech)
> instrukcje uzytkowników (yarp)

to ja mogę zrobić identyfikację aktorów razem z diagramem przypadków użycia, bezpieczeństwo i obczaić o co chodzi z testami w Unity.

raportujemy tutaj co robimy i co zrobiliśmy :) zaliczymy i będzie spokój. :+1:

**Comment by Lamb3rt** [comment]
jak mnie irytuje, że większość tych dokumentów i ogólnie cały proces produkcyjny według susłowa dotyczy wąskiej kategorii aplikacji i np. do gier w ogóle nie ma zastosowania

a i tak musimy się męczyć, bo nikt nam nie powiedział, że na projekt lepszy byłby kalkulator, a nie gra

**Comment by Lamb3rt** [comment]
spróbuje zrobić instrukcję, niezawodność iiii diagram klas

**Comment by yyarp** [comment]
model konceptualny (yarp) - to mamy, trzeba mapę myśli zrobić nową po prostu
opis funkcjonalny aplikacji (yarp)

**Comment by Lamb3rt** [comment]
https://www.dropbox.com/s/8j18kyubjutl732/diagramKlas.odt?dl=0 Wasza opinia?

**Comment by yyarp** [comment]
https://drive.google.com/folderview?id=0B7f_p3HHIh8lLWdlQVBzU2RVams&usp=drive_web weszły dwie wersje mapy myśli

**Comment by yyarp** [comment]
i dalej nie rozumiem o co chodzi z tym opis funkcjonalny aplikacji.
czy to ma być opis funkcjonalności? czy opis funkcji całego programu?

**Comment by czeskij** [comment]
http://i.imgur.com/W7sNVqY.png - use case diagram

bezpieczeństwo: 
* skrypty korzystają z wbudowanej w Unity3D funkcji Debug.Log(), która pozwala na informowanie developera o zdarzeniach w aplikacji na wybranym przez niego poziomie szczegółowości
* przechwytywanie wyjątków przy pomocy poleceń try/catch; ochrona głównie przed najczęściej występującym wyjątkiem znalezionym w fazie testów, MissingReferenceException

**Comment by czeskij** [comment]
zaliczone już dawno temu :D #zombieissue
