### ISSUE TITLE
kamerka lub generowanie

### ISSUE THREAD

**Issue by yyarp** [czeskij/GraIO#4]
na myśli mam konkretnie coś takiego: 
1) albo w trakcie kontroli zachowania kamery wyciągać z aplikacji dokładne granice okienka z wartościami
2) albo przy generowaniu platform zrobić może dodatkowo generowanie sceny, które daje nam na granicach okienka/przestrzeni gry jakiś collider
a to po to, żeby można było zrobić odbijanie się od ścian w przeciwnym kierunku i nie wylatywanie poza przestrzeń gry.
all comments and  ideas will be thoroughly investigated :)

**Comment by czeskij** [comment]
collidery so i działajo
